
import { AuthProvider } from "@/components/AuthProvider";
import "./../globals.css";
import { NavigationProgress } from "@/components/NavigationProgress";
import { Nav } from "@/components/layouts/Nav";
import { Footer } from "@/components/layouts/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Beranda | Temen Ngoding",
  description: "Generated by create next app",
};

export default function WebLayout({ children }: { children: React.ReactNode }) {
  return (

    <html lang="en">
      <body className="bg-[#F1F4F5] font-['Poppins']">
      <NavigationProgress/>
      <AuthProvider>
        <Nav />
          {children}
        <Footer />
      </AuthProvider>
      </body>
    </html>
    
  )
}